meta:
  hosts:
    novo:
      tags: [personal, gaming, laptop]
    thinkpad:
      tags: [personal, dev, laptop]
    beelink:
      tags: [server, mini]
    omen2:
      tags: [work, laptop]

apt:
  - git
  - vim
  - tmux
  - trash-cli
  - jq
  - wl-clipboard
  - xclip
  - htop
  - neofetch
  - inxi
  - smartmontools
  - xdg-utils
  - curl
  - wget
  - fdclone
  - ripgrep
  - pipx
  - glances
  - traceroute
  - build-essential
  - xdotool
  - wmctrl
  - pandoc
  - ncdu
  - lm-sensors
  - iw
  - iperf3
  - hostname
  - gedit
  - sqlitebrowser
  - rename
  - samba
  - ffmpeg
  - image-magick
  - grubconfig
  - gzip
  - cifs-utils

dotfiles:
  - .bashrc
  - .tmux.conf
  - .vim
  - .git
  - .config/fitviz
  
gnome:
  - shortcuts
  - terminal
  - filebrowser
  - trackpad

apps:
  - name: obsidian
    hosts: [novo, thinkpad, omen2]
  - name: google-chrome
    exclude: beelink
  - name: vscode
  - name: tailscale
    exclude: omen2
  - name: steam
    hosts: [novo, thinkpad]
  - recoll:
    hosts: [novo, thinkpad, omen2]

pipx:
  - name: fitviz
    hosts: [novo]
  - name: usage-logger
    hosts: [novo, thinkpad, omen2]

mounts:
  - 4tbdata
  - beelink1
  - 2tbdata